//
//  ViewController.swift
//  renato
//
//  Created by Aline Ebone on 20/02/20.
//  Copyright © 2020 Aline Ebone. All rights reserved.
//

import UIKit

class ViewController: UIViewController {

    @IBOutlet weak var wisdom: UITextView!
    
    let wisdomSentences = [
    "Não critique! Procure antes colaborar com todos, sem fazer críticas. A crítica fere, e ninguém gosta de ser ferido. E a criatura que gosta de criticar, aos poucos, se vê isolada de todos. Se ver alguma coisa errada, fale com amor e carinho, procurando ajudar. Mas, sobretudo, procure corrigir os outros, através de seu próprio exemplo.",
    "Deus está em toda parte ao mesmo tempo, ao redor de você, dentro de você! Jamais você está desamparado. Nunca está só. Não permita que a mágoa o perturbe: procure manter-se calmo, para ouvir a voz silenciosa de Deus dentro de você. Assim, poderá superar todas as dificuldades que aparecerem em seu caminho, e há de descobrir a Verdade que existe em todas as coisas e pessoas.",
    "Lembre-se de que colheremos, infalivelmente, aquilo que houvermos semeado. Se estamos sofrendo, é porque estamos colhendo os frutos amargos das sementeiras errôneas do passado. Fique alerta quanto ao momento presente! Plante apenas sementes de otimismo e de amor, para colher amanhã os frutos doces da alegria e da felicidade. Cada um colhe, exatamente, aquilo que plantou.",
    "Não deixe que a calúnia o perturbe! Todos nós estamos sujeitos à calúnia. Mas saiba superá-la, vivendo de tal maneira que o caluniador não tenha razão. Não revide um ataque com outro ataque. Não se magoe com o caluniador. Perdoe sempre. Apenas viva de tal maneira, que jamais o caluniador tenha razão.",
    "Os conselhos ajudam, não há dúvida. Mas não se esqueça de que a solução de nossos problemas está dentro de nós mesmos, nas voz silenciosa de nossa consciência, que é a voz de Deus dentro de nós. Não se deixe enganar: só você será o responsável pelo caminho que escolher. Ninguém poderá prestar contas por você. Procure, portanto, viver acertadamente, de acordo com sua consciência.",
    "Resolva seu problema! Há muito tempo você se propõe reformar sua vida, melhorar seus atos, cessar definitiva-mente suas fraquezas. Vamos, então, começar a partir deste momento! Não deixe para amanhã o que pode fazer hoje... De certo você não há de resolvê-lo do dia para a noite. Mas, comece já! E se cair de novo, não desanime: saiba recomeçar quantas vezes for preciso!",
    "Embora sozinho, continue a caminhada! Se todos o abandonarem, prossiga sua jornada. Se as trevas crescerem em seu redor, mais uma razão para que você mantenha acesa a pequenina chama de sua fé. Não deixe que sua luz se apague, para que você mesmo não fique em trevas. Ilumine, com sua luz, as trevas que o circundam.",
    "Cada um de nós é responsável por seus atos. Por que vai desanimar, pelo que os outros fizeram a você? Que tem você a ver com isso? Siga à frente, ainda que o mundo inteiro esteja contra você. Você há de vencer, mesmo que fique sozinho. Continue sem desânimo, porque você é o único responsável por seus atos.",
    "Nossa mente está mergulhada na Mente Divina que sustenta os universos infinitos. Nossa força mental permanece impregnada da Força Mental divina, que está em toda parte ao mesmo tempo. Procure manter-se unido a essa Força Infinita, e jamais será derrotado. Você tem esse poder: confie! Você vencerá em toda a linha, se o quiser.",
    "Modifique seu modo de pensar, para que sua saúde se firme e estabeleça. Pare de queixar-se de doenças! A doença é aumentada pela nossa emissão mental negativa. Expulse a enfermidade, confiando em sua cura! Você pode curar-se! Você está melhorando cada dia mais, sob todos os pontos de vista.",
    "Aprenda a repousar sua mente. A mente cansada não pode pensar direito. Repouse a mente, fazendo o exercício da Higiene Mental, para conquistar cada vez maior energia e vigor. O cérebro cansado turva o pensamento. E o pensamento é a maior força criadora que existe sobre a terra. Repouse o cérebro, para pensar com acerto e alegria.",
    "Não aceite maus conselhos! Não se deixe sugestionar por palavras de desânimo! Sempre existe uma saída para qualquer problema, por mais complexo e difícil que nos pareça. A Força Divina que rege os universos está dentro de nós. Ligue-se ao Pensamento Universal de Bondade e Amor, e vencerá todos os obstáculos.",
    "Pense positivamente! Nossos pensamentos emitem ondas reais que se irradiam de nosso cérebro, formando uma atmosfera mental que é peculiar a cada pessoa. De acordo com o tipo de vibração do pensamento, atrairemos a nós todas as ondas semelhantes. Se você pensar negativamente, atrairá todos os pensamentos negativos, piorando seu estado. Pense positivamente, para atrair apenas pensamentos positivos de paz e prosperidade.",
    "Mantenha uma atitude vitoriosa! Quando você olha para uma pessoa curvada e triste, perde a confiança, porque verifica que está abatida e preparada para uma derrota. Não deixe que ninguém pense isso a seu respeito! Mantenha-se de cabeça erguida, confiante e risonho, e todos confiarão em você. Irradie força e entusiasmo até por meio da atitude de seu corpo.",
    "Não esteja ansioso e preocupado, para não atrair moléstias para seu corpo. A ansiedade é um fator bioquímico, que influencia as secreções glandulares, produzindo demasiada adrenalina, que estimula em exagero o sistema nervoso. Daí à enfermidade é um passo. O nervosismo prejudica fundamentalmente a saúde. Portanto, não seja ansioso: faça constantemente afirmações positivas de saúde, e mantenha-se calmo e sereno.",
    "Você jamais está abandonado! Absolutamente! O Pai não abandona ninguém. Ele veste de plumas multicolo-ridas as pequeninas aves, enfeita de beleza e perfume as flores e não deixa morrer de fome nem os insetos nem os pequeninos vermes. Esteja certo: não cai um fio de cabelo de sua cabeça, sem que Ele o permita. Confie no Pai! Você jamais está abandonado!",
    "Afaste de si o veneno da lisonja. Não creia naqueles que o elogiam sem motivo. Prefira ouvir uma crítica honesta, a um galanteio vazio. A crítica aos nossos atos poderá trazer-nos o alerta de que necessitamos para corrigir-nos. O elogio fácil nos amolece e ilude. E nada existe de mais frágil que uma criatura iludida a seu próprio respeito.",
    "Seja o mesmo, dentro e fora do lar. O lar é a sociedade em miniatura! A sociedade é o lar ampliado. Num e noutra, seja o mesmo: firme em sua palavra, seguro em seu pensamento, honesto em seus atos, calmo na confiança em si mesmo. O homem é o que é. E a manifestação externa reflete o estado íntimo de nossa alma.",
    "Seja atencioso e compreensivo. Quantas vezes a pessoa que vem falar com você traz problemas recônditos, escondidos no âmago da alma! Mantenha-se sereno, você que já vislumbrou a luz do entendimento fraterno. Conserve seu equilíbrio, quando alguém se apresenta perturbado. Seja atencioso e compreensivo: o mundo está repleto de enfermos, e você tem saúde moral.",
    "Não procure evidência pessoal. Reflita que, quanto mais exposto à visão alheia, mais se tornará alvo de ciúme e inveja. As vibrações negativas, mesmo que não lhe façam mal, positivamente, poderão cansá-lo, no trabalho de defender-se. Procure agir discretamente, embora com firmeza, deixando que os vaidosos e vazios se exponham numa evidência de que você, certamente, não necessita para brilhar. O vidro comum brilha muito ao sol, mas o brilho do ouro está escondido no cofre: nem por isso valerá menos que o vidro...",
    "Evite o luxo supérfluo. Tudo o que sobrecarrega o ambiente atrapalha a vida. Seja sóbrio e natural. O artificialismo distorce e causa fadigas inúteis. A sobriedade repousa o espírito e o corpo. Seja sóbrio e natural em tudo, desde a sua pessoa, até o mobiliário de sua casa. Quem pouco tem é que procura mostrar mais do que possui.",
    "Cumprimente a seus amigos com alegria. Muitas vezes, uma simples saudação alegre e espontânea conquista um coração e consola uma dor. A saudação triste e acabrunhada pode instilar veneno num coração alegre. Derrame alegria e bondade, ao encontrar uma pessoa conhecida, e já terá conquistado os benefícios de uma boa ação meritória. Que seus amigos sintam o calor de seu coração afetuoso no simples cumprimento alegre.",
    "Trate com afabilidade a todos. O vizinho que senta a seu lado na condução não é seu inimigo, nem seu concorrente. Trata-se, sempre, de seu irmão, a quem você precisa acolher com simpatia. Não procure brigar com ele, para conquistar maior conforto: dê você mais conforto a ele. Mesmo insensivel-mente, você receberá de volta as vibrações de gratidão de seu coração.",
    "Se alguém queixar-se da vida a seu lado, responda com palavras de encoraja-mento. Não aumente o peso a quem já sente demasiado o peso que carrega. Se alguém se lamenta da vida, procure mostrar os lados bons e belos da existência. Não contribua com suas pró-prias lamentações para o desânimo do companheiro. Reanime-o com esperança e com bom ânimo, com palavras de incentivo e coragem. Talvez desse remédio dependa a cura de seu coração desalentado.",
    "Desperte! Não deixe que a rotina arrase sua vida! Execute sua tarefa com amor sempre renovado, porque isto trará alegria a você mesmo. A rotina cansa e corrói a alma, desalenta e carcome o entusiasmo. Renove cada manhã seu armazenamento de alegria de viver. Ajude a todos e cumpra alegremente sua tarefa, para receber de volta o benefício da felicidade de seu trabalho.",
    "Afaste-se dos ambientes mal-sãos. Evite as pessoas mal intencionadas. No entanto, se sua presença puder melhorar, sem que com isto sofra sua alma, leve sua virtude mesmo ao antro do vício. Mas faça como o sol, que ilumina e saneia o pântano, sem que seu raio de luz e calor dali se afaste enlameado e fétido. Seja você o espelho vivo de sua fé.",
    "Não condene os que estão em posição de destaque na política ou na administração pública. Não diga que no lugar deles faria melhor. Enquanto não pomos em ação real nossas forças, não temos certeza do que são capazes. Talvez você fizesse pior, se estivesse na posição deles. Procure desculpar, porque não conhecemos as circunstâncias em que se encontram aqueles que têm sobre seus ombros o grande peso da responsabilidade pública.",
    "Visite os pobres e enfermos. Pelo menos uma vez por semana dedique algumas horas a consolar um coração aflito. O consolo que você levar, mesmo com sacrifício de sua parte, é a garantia de que está cumprindo um dever de cristão e de homem. Não espere que o procurem, para agir fraternalmente, amparando os fracos e confortando os tristes. Nem pense que você está dando mais do que recebe: quem consola um coração triste, na realidade recebe muito mais do que dá.",
    "Eleve seu coração em prece! Mas evite recitar fórmulas lidas ou decoradas. Que de seu coração partam as palavras espontâneas, como você faz quando conversa com um amigo querido. Prece não é obrigação que alguém desempenhe para \"ver-se livre de um peso\". Ore fervorosamente, mas sentindo as palavras que profere, para que a ligação com as Entidades angélicas seja efetiva e real. Faça da oração um hábito indispensável à saúde espiritual.",
    "Não transforme sua prece em petitório insistente! \"O Pai sabe aquilo de que necessitamos, mesmo antes de pedirmos\". Quando quiser alguma coisa para si, peça-o também para os outros, para todos os que estiverem nas mesmas condições. No momento da prece, evite o egoísmo. A prece é a melhor ocasião de demonstrarmos nosso amor. E pedindo para todos, com amor, seremos os primeiros a receber o benefício. Quem acende uma luz, é o primeiro a iluminar-se."
    ]
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        wisdom.text = ""
    }

    @IBAction func generateWisdom(_ sender: Any) {
        wisdom.text = wisdomSentences.randomElement();
    }
    
}

